name: Deploy Static Website

on:
  push:
    branches:
      - main  # or 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
